### ISSUE TITLE
Better document fill_value argument of read_*()

### ISSUE THREAD

**Issue by alixdamman** [larray-project/larray#1020]
Reported by user GT.

He got nan instead of 0 although passed `fill_value=0` to read_excel().

**Comment by gdementen** [comment]
(I am going to ask gt)

**Comment by gdementen** [comment]
In fact, there was no bug at all: just a misunderstanding of what fill_value does.

**Comment by gdementen** [comment]
will change the meaning of the argument in #1028 instead of changing the documentation
