### ISSUE TITLE
implement larray_equiv and larray_nan_equiv

### ISSUE THREAD

**Issue by gdementen** [larray-project/larray#237]
larray_equal is very picky (axes in same order and no broadcasting)

**Comment by gdementen** [comment]
Maybe more arguments to LArray.equals? See #488

**Comment by alixdamman** [comment]
@gdementen In which context that would be useful?

**Comment by gdementen** [comment]
In most contexts. Users usually do not care that axes are ordered differently when comparing two arrays. So we might want to make this the default. Also, currently, you cannot compare an array with a scalar, or to another array with less axes:

```python
>>> arr1 = ndtest(2)
>>> arr2 = full('a=a0,a1;b=b0..b2', arr1)
>>> arr2['a0'].equals(0)
False
>>> arr2.equals(arr1)
False
>>> arr2.equals(arr2.T)
False

but...

>>> arr2 == arr1
a\b    b0    b1    b2
 a0  True  True  True
 a1  True  True  True
>>> (arr2 == arr1).all()
True
>>> arr2 == arr2.T
a\b    b0    b1    b2
 a0  True  True  True
 a1  True  True  True
```
