### ISSUE TITLE
cleanup unit tests

### ISSUE THREAD

**Issue by gdementen** [larray-project/larray#26]
we should rewrite most LArray unit tests using small-ish arrays created using ndtest() instead of the current demo-related examples.

**Comment by alixdamman** [comment]
cleanup + use a more `pytest` like syntax --> https://docs.pytest.org/en/latest/assert.html

**Comment by gdementen** [comment]
we have 2 separate issues here: the "content" of the tests (ie use smaller test arrays mostly created using ndtest) and the "format" of the tests (ie pytest syntax instead of unittest syntax). We can of course tackle both at the same time, but we do not have to.

**Comment by alixdamman** [comment]
issue #237 should be fixed in the same time.

**Comment by alixdamman** [comment]
to convert nosetests to pytest : https://github.com/pytest-dev/nose2pytest
