### ISSUE TITLE
implement set_printoptions or something similar

### ISSUE THREAD

**Issue by gdementen** [larray-project/larray#274]

**Comment by gdementen** [comment]
https://stackoverflow.com/questions/22222818/how-to-printing-numpy-array-with-3-decimal-places

**Comment by alixdamman** [comment]
See also how ``xarray`` implement options : https://github.com/pydata/xarray/blob/656f8bd05e44880c21c1ad56a03cfd1b4d0f38ee/xarray/core/options.py
