### ISSUE TITLE
only use .h5 as input in tutorial so that we can ship less files?

### ISSUE THREAD

**Issue by gdementen** [larray-project/larray#421]
ie generate .csv and .xlsx from those.

But only if we can do this without impacting the readability of the tutorial.

**Comment by alixdamman** [comment]
Using the "pseudo-decorator" @suppress and @verbatim ( http://matplotlib.org/sampledoc/ipython_directive.html#pseudo-decorators ), it should be possible.

**Comment by gdementen** [comment]
That would be problematic, because then users couldn't run the tutorial by themselves.

**Comment by alixdamman** [comment]
That means we need to inverse sections "load" and "save" in the tutorial but it is less logic to me.

**Comment by gdementen** [comment]
A few small csv certainly do not hurt. .xlsx are bigger but if the dataset is small, the size is reasonable.

I think a better option is to ship smaller datasets instead. Closing as wont fix.
