### ISSUE TITLE
use raw docstrings (r"""bla""") to avoid having to escape \

### ISSUE THREAD

**Issue by gdementen** [larray-project/larray#477]
We need to test it then decide whether we use it everywhere for consistency or only where necessary.

Special mention for LArray and AxisCollection.split_axes, from_list and from_string which need quadruple \ !

**Comment by alixdamman** [comment]
Seems legit ([PEP 257](https://www.python.org/dev/peps/pep-0257/)):

> For consistency, always use """triple double quotes""" around docstrings. Use r"""raw triple double quotes""" if you use any backslashes in your docstrings. For Unicode docstrings, use u"""Unicode triple-quoted strings""".
