### ISSUE TITLE
move larray repository to larray-project

### ISSUE THREAD

**Issue by gdementen** [larray-project/larray#502]

**Comment by alixdamman** [comment]
reminder : update all links to larray github rep in larray, larray-editor, larray_eurostat and larray-feedstock (conda-forge).

**Comment by alixdamman** [comment]
@gdementen 
I suggest to follow these steps:
1. release ``larray 0.28`` 
2. move ``larray`` github repo from liam2 to larray-project  
3. merge PR https://github.com/larray-project/larray-editor/pull/139 (larray-editor)
4. release ``larray-editor`` and ``larray-eurostat``
5. merge PR #600 (larray)

**Comment by gdementen** [comment]
Is there a good reason for this odd order? I expected the simpler approach of moving the repo, then update everything (merge PR) then release all projects together?

**Comment by alixdamman** [comment]
Well, the only reason is superstition. OK to move first.

**Comment by gdementen** [comment]
😄

**Comment by alixdamman** [comment]
I do the move or you do?

**Comment by gdementen** [comment]
I thought you would do it. Do you want me to do it?

**Comment by alixdamman** [comment]
No, I will do it.

**Comment by alixdamman** [comment]
Done

**Comment by alixdamman** [comment]
Waiting for PR #600 and PR https://github.com/larray-project/larray-editor/pull/139 to be merged before to close this issue

**Comment by alixdamman** [comment]
closed by PR #600

**Comment by alixdamman** [comment]
Link to github repo must also be changed in ``larray-feedstock`` repository

**Comment by alixdamman** [comment]
Done by https://github.com/larray-project/larray-feedstock/commit/0eea888b64e0cc943f5e9b66e838e611adb1164b
