### ISSUE TITLE
Drop Python 2 support

### ISSUE THREAD

**Issue by alixdamman** [larray-project/larray#567]
@gdementen Not soon but my idea is then to open an issue to implement [type hints](https://docs.python.org/3/library/typing.html).

**Comment by gdementen** [comment]
Type hints work on python2 too (using comments). See liam2/liam2#258

**Comment by alixdamman** [comment]
I know but I don't want to mix comments and Python 3 type hints. I prefer to wait until we drop Python 2 support.

**Comment by alixdamman** [comment]
Given your comment https://github.com/larray-project/larray/pull/840#issuecomment-588187438 , Do you mind if I start to work on this? 

Of course, I will not merge anything until you released the 0.32.2 version of larray.

**Comment by gdementen** [comment]
sure, go ahead

**Comment by gdementen** [comment]
and you can merge this to master too, given that I will need to release from a branch anyway (to avoid introducing #842 in a patch release)
