### ISSUE TITLE
Update LArray to support Pandas >= 0.21

### ISSUE THREAD

**Issue by alixdamman** [larray-project/larray#569]

**Comment by gdementen** [comment]
what do you mean?

**Comment by alixdamman** [comment]
It was 0.21 and not 0.13, sorry. The version 0.21 of Pandas breaks lots of our IO methods.

**Comment by gdementen** [comment]
I wonder if it is not a bug. We should first create a test case reproducing
the problem using only Pandas to see if that is reasonable behavior on the
part of Pandas. If it's not report a bug.

**Comment by alixdamman** [comment]
One part of the explanation : https://pandas.pydata.org/pandas-docs/version/0.21/whatsnew.html#multiindex-constructor-with-a-single-level
