### ISSUE TITLE
Update "How to contribute" page

### ISSUE THREAD

**Issue by alixdamman** [larray-project/larray#584]

**Comment by alixdamman** [comment]
See PR #583

**Comment by gdementen** [comment]
doh, you beat me to create the issue :)

Copy paste from #585 :
* update the git workflow to mention fork, upstream, origin & PR (possibly link to other resource explaining that)
* need to state that they accept to release their contribution and any future contribution to the project under the license of the project.
* update sections about tests: how write them and how to run them.
* git for windows is not at: https://gitforwindows.org/

**Comment by gdementen** [comment]
* do not rebase while a PR is being developed to ease reviewing but rebase to clean up commits just before it is merged
* when/how to ask for review (we might want to remove the ready for review tag which we do not use anymore)

**Comment by gdementen** [comment]
* commit message guidelines? (e.g. fix #xxx)

**Comment by gdementen** [comment]
* PRs should provide a changelog entry, new tests and update/expand documentation if applicable

**Comment by alixdamman** [comment]
TODO:

- [ ] update the git workflow to mention fork, upstream, origin & PR (possibly link to other resource explaining that)
- [ ] need to state that they accept to release their contribution and any future contribution to the project under the license of the project.
- [ ] PRs should provide a changelog entry, new tests and update/expand documentation if applicable
- [ ] update sections about tests: how write them and how to run them.
- [ ] git for windows is now at: https://gitforwindows.org/
- [ ] do not rebase while a PR is being developed to ease reviewing but rebase to clean up commits just before it is merged
- [ ] commit message guidelines? (e.g. fix #xxx)
