### ISSUE TITLE
update Session.equals to also test Axis and Group objects

### ISSUE THREAD

**Issue by alixdamman** [larray-project/larray#610]
@gdementen also add ``Session.axis_equals`` and ``Session.group_equals``?

**Comment by gdementen** [comment]
> update Session.equals to test also Axis and Group objects?

yes!

> also add Session.axis_equals and Session.group_equals?

no. If somebody wants to do that, he should use Session.filter(kind=Axis).equals and Session.filter(kind=Group).equals instead.
