### ISSUE TITLE
rename LArray class to Array?

### ISSUE THREAD

**Issue by gdementen** [larray-project/larray#611]
Pros:
* We are in the larray module, so the L of LArray is kinda redundant
* It would be one less character to type
* The L of LArray is a bit weird for arrays without labels (arrays with only wildcard axes)
* I like it :)

Cons:
* more deprecated warnings for existing users (though a single string replace could fix the problem)
* LGroup will look slightly odd (but having Group and IGroup would be worse). On the other hand, if we converge both kinds of groups to Group (like I discussed in a few issues) this would no longer be a con but a pro.

**Comment by alixdamman** [comment]
Why not. I always found weird to have a specific object with the same as the library. 
But considering users hate syntax change and love stability I would to move this issue for milestone 0.32 or later.

**Comment by alixdamman** [comment]
In that case, I think we should also use Frame instead of LFrame for issue #81, right?

**Comment by gdementen** [comment]
> In that case, I think we should also use Frame instead of LFrame for issue #81, right?

Sure
