### ISSUE TITLE
add 'outer' method

### ISSUE THREAD

**Issue by alixdamman** [larray-project/larray#643]
Same as Numpy [outer](https://docs.scipy.org/doc/numpy/reference/generated/numpy.outer.html) function

**Comment by gdementen** [comment]
What's the use case for this?

**Comment by alixdamman** [comment]
One of our current users (from the I/O team) required to make an outer product with 2 vectors of length (255) and (144) to get a (255, 144) output array.

**Comment by gdementen** [comment]
But this works by default, right?

```python
>>> a = ndtest(3); b=ndtest('b=b0..b2') + 5
>>> a * b
a\b  b0  b1  b2
 a0   0   0   0
 a1   5   6   7
 a2  10  12  14
```

**Comment by alixdamman** [comment]
Completely forgot about that. Sorry.
