### ISSUE TITLE
remove LArray.insert pos and axis arguments

### ISSUE THREAD

**Issue by gdementen** [larray-project/larray#652]
this is a leftover from our general change from position to index

**Comment by gdementen** [comment]
if we do it, it should happen in 0.29, because I am currently implementing (or rather cleaning up one of the myriad features I have implemented partially in the train) .delete which needs the same argument

**Comment by alixdamman** [comment]
Let's do it

**Comment by gdementen** [comment]
@alixdamman This needs to happen in 0.29, or we defer .delete to 0.30

**Comment by alixdamman** [comment]
Changed to 0.29

**Comment by gdementen** [comment]
now I am wondering if this argument (and axis) shouldn't be simply removed (from both insert and drop). To work using indices one can always use an IGroup:
```python
array.insert(value, before=axis.i[1])
```
and if one does not have the axis available, either the X notation or the string notation can help:
```python
array.insert(value, before=X.axisname.i[1])
array.insert(value, before='axisname.i[1]')
```

**Comment by alixdamman** [comment]
OK. Let's remove pos/indices from insert and drop.
