### ISSUE TITLE
Make Axis.by() generate a list of named groups instead of anonymous groups

### ISSUE THREAD

**Issue by alixdamman** [larray-project/larray#669]
@gdementen good idea or bad idea?

**Comment by gdementen** [comment]
As I explained, I don't think this is necessary. Besides, in the future, .by() should create a Grid I think. I know you still haven't seen that but a "preliminary" version of this will be coming "soon" so that you can at least see what this is all about even though it is not ready yet.

**Comment by alixdamman** [comment]
Closed because not necessary
