### ISSUE TITLE
provide better docstrings for ufuncs

### ISSUE THREAD

**Issue by gdementen** [larray-project/larray#700]
The numpy examples in the ufuncs doc (floor, ceil, trunc, sqrt, ...) are confusing our users.

round does not have any example either.

**Comment by alixdamman** [comment]
What do you suggest?
To add a warning at the beginning of the documentation like xarray does (see http://xarray.pydata.org/en/stable/generated/xarray.ufuncs.angle.html#xarray.ufuncs.angle for examples) or to write our own documentation and examples for each ufunc?

**Comment by gdementen** [comment]
Writing our own doc for **all** ufuncs would take too much time at this point. We could have an hybrid approach: write our own doc for the few ufuncs which are very important to our users and add a warning like xarray for the others. I consider the following ufuncs very important:
* **where, minimum, maximum** -- those needs to be both documented and have specific examples because broadcasting by axes names makes them more user-friendly than their numpy version.
* round, floor, ceil, trunc, isnan, isinf, sqrt, log, exp, inverse -- at least those need to appear in the API doc and ideally have our own examples.
* interp -- should appear in the API doc **if** it actually works with LArrays, which I have never tested. Might be worth having specific documentation if it works well.
* all other ufuncs should have the numpy doc with a warning.
