### ISSUE TITLE
cleanup modules namespaces

### ISSUE THREAD

**Issue by alixdamman** [larray-project/larray#737]
@gdementen Looking at other libraries, it sounds more usual to avoid from .... import * and to put `__all__` lists in `__init__` files (see xarray for example: https://github.com/pydata/xarray/search?q=__all__&unscoped_q=__all__)

Currently, when you do 
```python
from larray import *
```
you import a lot of stuff from util/misc.py that should be only for internal use.

**Comment by gdementen** [comment]
I don't really care about removing the "import *" from our code (if we have `__all__` in the imported module, that is fine with me) but I **do** care that our current top-level namespace is polluted with a lot of junk that should not be there. I thought I had already opened an issue for this (at least I meant to do that for a long time) but I just checked and there is not.  Basically, I am +1 on cleaning up the top-level namespace, I am +0 on cleaning up individual namespaces and -0 on removing `import *` internally (but adding `__all__` to some modules might be necessary).
