### ISSUE TITLE
Set None as default value for a_min and a_max arguments of LArray.clip method

### ISSUE THREAD

**Issue by alixdamman** [larray-project/larray#747]

**Comment by gdementen** [comment]
might be a good opportunity to change the argument names. a_min & a_max are inherited from numpy and the a_ prefix is mostly arcane IMO. Calling them vmin & vmax or minval & maxval or something like that would make more sense IMO (simply min & max might be even more intuitive but those are builtin names so I am unsure about that... we have a precedent of using an argument named filter though).
