### ISSUE TITLE
question: how to use larray to save a pandas dataframe to liam2 csv file ?

### ISSUE THREAD

**Issue by benjello** [larray-project/larray#750]
I have a pandas dataframe that I want to save for later use with liam2.
My dataframe has a MultiIndex on axis 0 and only one column.

````
array = larray.from_frame(df)
array.to_csv('test.csv', dialect = 'liam2')
`````
The file produced does not have the two lines header of liam2 csv files.

Any hint @gdementen ?

Thanks !

**Comment by gdementen** [comment]
This is not done yet. See: https://github.com/larray-project/larray/issues/433. Would be a nice PR though 😉
