### ISSUE TITLE
stack: if elements is a dict or a Session, passing name as axis should be enough

### ISSUE THREAD

**Issue by alixdamman** [larray-project/larray#755]
if elements is a dict or a Session, the new axis should be build by taking the keys as labels if passed value for `axis` argument is simply the name of the new axis.

**Comment by gdementen** [comment]
see #581

**Comment by gdementen** [comment]
not a bug though

**Comment by gdementen** [comment]
@alixdamman for dict elements, this is done. For a Session, I haven't tested but I don't think passing a single session to stack all its arrays ever worked?! Was that what you meant? If so, please open a new issue. It should be easy to make that work: only changing the "if isinstance(elements, dict):" to "if hasattr(elements, 'items'):" should be enough I think.
