### ISSUE TITLE
Drop Python 3.5 support

### ISSUE THREAD

**Issue by alixdamman** [larray-project/larray#767]
I noticed that the recent versions of conda packages like numpy, pandas, pytables and maybe others stopped to support Python 3.5

It is maybe the time to drop the support of Python 3.5

But this make think that we need to find an easy and automatic way to upgrade the Python version in our current users. The upgrade is very simple and consists in typing ``conda install python=3.7`` but finding the command prompt is not that easy for all our users.
Maybe adding an new entry "Upgrade Python Version" in the "LArray" Windows menu could be enough?

**Comment by gdementen** [comment]
+1 for dropping python 3.5 support.
-1 for upgrade python version windows menu. What we need is a fixed python version in fpb_py_env (or whatever we call that package -- I would rather have it as a separate package from larrayenv), and that package should bring a "Upgrade Python/LArray" menu item with it.

**Comment by alixdamman** [comment]
Not sure to follow you. You want to create a new sub-project containing only a "conda recipe" directory with a equivalent mechanism as in the larray-editor project to add a new item in the LArray Windows menu?

**Comment by gdementen** [comment]
Indeed. Is there anything wrong with that?

**Comment by alixdamman** [comment]
closed by commit 099cc4a50c96733e71278bd1ee5b6fc124d024ca
