### ISSUE TITLE
implement arbitrary metadata for LArray objects

### ISSUE THREAD

**Issue by gdementen** [larray-project/larray#78]
all array creation functions should be updated + I/O functions
we probably want to generalize to any metadata (store title and description in a .meta dictionary) or something like that.

**Comment by alixdamman** [comment]
## Let us sum up a little bit:

1. access name: 
`meta` or `attrs`?
`meta` would be nice if we want one day implement IO functions `from_xarray` and `to_xarray`.

2. passing metadata at array creation:
- solution a: by passing an (ordered) dict 
  ```python
     >>> arr = LArray(data, axes, {'title': 'my title'})
  ```
- solution b: via kwargs?
  ```python
     >>> arr = LArray(data, axes, title='my title')
  ```

3. What to do with current argument `title`?
- solution a: implement "blessed" metadata. Question is "which ones?" 
- solution b: passing metadata via kwargs.
- solution c: if we pass metadata via a dict and we do not implement blessed metadata, we could keep current `title` argument for some releases and display a FuturWarning   

4. Usage:
Current proposal is:
```python
   # add new metadata
   >>> arr.attrs.creation_date = datetime(2017, 2, 10)
   # access metadata
   >>> arr.attrs.creation_date
   datetime.datetime(2017, 2, 10, 0, 0)
   # modify metadata
   >>> arr.attrs.creation_date = datetime(2017, 2, 16)
   # delete metadata
   >>> del arr.attrs.creation_date
```

**Comment by gdementen** [comment]
I mostly have still the same opinion.
1.  either is fine by me. I have a slight personal preference for .attrs but **_we need to poll our users_** to see what is most intuitive for them.
2.  a) must be implemented in any case to disambiguate metadata keywords which collide with other arguments. 
  b) could be done in addition, but I am reluctant to do it because that means that **all** array creation functions should treat extra kwargs like metadata and it means the list of "forbidden" metadata keywords is different depending on the function. It is also problematic for `stack()` which already uses kwargs for something else. Also, providing a way to set metadata could be useful in fact for any method returning an LArray (and some of them already uses **kwargs for other purposes e.g. aggregates) and loosing argument names validation (which is the flip side of the coin when you use **kwargs) for all methods is a heavy price to pay IMO.
3. given the above, either solution a or c. We could postpone the decision by starting with only "title" as a blessed argument, and later either deprecate it or add a few other "blessed" arguments depending on how it goes.
4. ok

**Comment by alixdamman** [comment]
## Specifications for metadata:

1. Usage:
```python
   # add new metadata
   >>> arr.attrs.creation_date = datetime(2017, 2, 10)
   # access metadata
   >>> arr.attrs.creation_date
   datetime.datetime(2017, 2, 10, 0, 0)
   # modify metadata
   >>> arr.attrs.creation_date = datetime(2017, 2, 16)
   # delete metadata
   >>> del arr.attrs.creation_date
```

2. Passing metadata at array creation:
Users do it by passing an (ordered) dict 
  ```python
     >>> arr = LArray(data, axes, attrs={'title': 'my title'})
  ```

3. Backward compatibility with argument `title` of LArray.init:
We implement a "blessed" metadata `title`. 

4. When copying metadata:
- [ ] `arr.copy()`
- [ ] `arr.set_axes()`

**Comment by gdementen** [comment]
1. I would still like to poll our users for deciding attrs vs meta (unless you did already). Maybe they don't care, maybe they do.
2. This is also possible:
```python
>>> arr = LArray(data, axes, Attrs(title='my title'))
```
and I think it would be useful to implement this **in addition** to the dict syntax, in the same vein that we support an AxisCollection object or a string or xyz... We do not necessarily need to advertise this though.

**Comment by alixdamman** [comment]
How would like to make the poll? Via the Google group `larray-users`? Mail?

**Comment by alixdamman** [comment]
Result of the poll is ``meta``

**Comment by gdementen** [comment]
Please keep a backup of your branch somewhere so that if we change our minds (or are pressured to do so) you do not need to redo everything...
