### ISSUE TITLE
implement AxisCollection.set_labels

### ISSUE THREAD

**Issue by gdementen** [larray-project/larray#782]
The name is provisional, but it should include most of the code currently in LArray.set_labels

**Comment by alixdamman** [comment]
Please, always set a milestone when you add a new issue.

**Comment by gdementen** [comment]
Why? Except for the next milestone, it is a waste of time IMO because priorities change all the time.

**Comment by alixdamman** [comment]
Because we have 7 pages of issues and I find easier to assign a milestone to all issues even it is temporary. But OK, this is too much.
