### ISSUE TITLE
make test data smaller

### ISSUE THREAD

**Issue by gdementen** [larray-project/larray#785]
For a reason which escapes me, population_session.h5 is 3Mb (while the same data in .xlsx is 11.8Kb) and demography.* are a bit large too, making the total size of the larray package larger than I would prefer.

**Comment by alixdamman** [comment]
In the PR #771 I have started to replace the use of _demography_ dataset by the _larray_eurostat_ dataset (which is actually population_session renamed). 

Is _demography_ used in the unittests?

**Comment by gdementen** [comment]
I don't remember...

**Comment by alixdamman** [comment]
I temporarily changed the name of _demography_, ran the tests and found that _demography_ is only used in the `load_example_data()` function and in the tutorial.

However, there is still a weird problem with _demography_eurostat.h5_. I'll take a look.

**Comment by alixdamman** [comment]
After some tests I discovered that the size of _demography_eurostat.h5_ is huge because the session contains Axis objects with labels of dtype '<U'.

**Comment by gdementen** [comment]
can we solve this?

**Comment by alixdamman** [comment]
We need to convert unicode labels to bytes
