### ISSUE TITLE
Tutorial: some changes

### ISSUE THREAD

**Issue by gdementen** [larray-project/larray#829]
- [x] rename pop variable to population everywhere
- in relabelling section:
   - [x] move set_labels(dict) before set_labels(list) and set_labels(func), because this the simpler, most useful version.
  - [x] add a big fat warning about set_labels(list) in both the tutorial and api doc because this is a big source of mistake

**Comment by alixdamman** [comment]
In arithmetic operations:
 
- Add more example of broadcasting.
- Replace examples with aggregation matrices by something else.

**Comment by alixdamman** [comment]
- rename section "Load And Dump Arrays, Sessions, Axes And Groups" as "Load And Dump Arrays"
- move subsection "Loading and Dumping Sessions" to "Working With Sessions"

**Comment by gdementen** [comment]
* add an example of .clip with arrays as minval and maxval (at least in API doc, and possibly in tutorial too)

**Comment by alixdamman** [comment]
- split the "Transforming Arrays" section into "Manipulating Array Axes", "Combining Arrays" and "Aligning Arrays".

**Comment by alixdamman** [comment]
Add more examples of how to use the `plot()` method

**Comment by gdementen** [comment]
> 
> 
>     * split the "Transforming Arrays" section into "Manipulating Axes And Labels of Arrays", "Combining Arrays" and "Aligning Arrays" sections.

Aligning Arrays is not a very intuitive section title. I am unsure what's better, but I doubt users would know what it means.
