### ISSUE TITLE
Use type hints for returned objects

### ISSUE THREAD

**Issue by alixdamman** [larray-project/larray#864]
Now we officially do no longer support Python versions under 3.6, it is (maybe) the right time to introduce type hints the code of LArray.

**Comment by alixdamman** [comment]
The idea behind is to (as for the ``ConstrainedSession``, see #832) enable auto-completion on PyCharm. When users write something like:
```python
arr = ndtest((3, 3)).transpose()
arr.
```
PyCharm doesn't know that the tranpose() method returns an array and then writing ``arr.`` below the call to transpose() doesn't make PyCharm to propose any auto-completion on Array's methods.

In other words, I am mostly interested to specify the type of the returned object by a method than to specify the type of each argument.

> It is a good idea to at least experiment with this but I wonder how to avoid duplication with what we have in the docstrings. Do you have an example of project using numpydoc style docstrings also using type hints?

xarray partly does: https://github.com/pydata/xarray/blob/c788ee44008cdd65c8b6de40c737f1b28e173496/xarray/core/variable.py#L65 

I don't know about pandas but they have a [_typing_.py](https://github.com/pandas-dev/pandas/blob/master/pandas/_typing.py) module.

> Assuming we go down that path (this needs a bit of research before we decide), I wonder what is the best strategy: all at once (a very large task) or as we go.

We can start with the type of the returned object if there is one. In that case, I can try to do it for all functions and methods.

**Comment by gdementen** [comment]
Ok, I missed that relatively recent development of things. It seems like the community is moving towards type hints **in addition to** numpydoc style docstrings. As you say, the return type is the most important and less verbose change, so we can start with that.
