### ISSUE TITLE
implement allclose or something similar

### ISSUE THREAD

**Issue by gdementen** [larray-project/larray#871]
It is simply annoying to have to type:

```python
arr1.equals(arr2, atol=1e-08, nans_equal=True)
```

PS: I am thorn about whether nans_equals should default to True or False in that case. On one hand, in 99.9% cases, I want nans_equal=True, so it would be nice to have a method with such a default to avoid having to type it each time (or worse... usually forgetting to type it then notice my result is False... investigate why... and only notice that it was because it had nans and I forgot to specify the arg). On the other hand having a different default than in equals could be confusing and having it default to True could lead, in some very rare case, to nan results being unnoticed, i.e. a silent error, which is what a library (and larray even more so) should strive to avoid.

**Comment by gdementen** [comment]
This is a follow-up to #488.

**Comment by alixdamman** [comment]
The `equal_nan` argument of the numpy [allclose](https://numpy.org/doc/stable/reference/generated/numpy.allclose.html) function has False as default value. 

Also, I think it wouldn't hurt to also implement an LArray version of the numpy [isclose](https://numpy.org/doc/stable/reference/generated/numpy.isclose.html#numpy.isclose) function.

**Comment by gdementen** [comment]
> The `equal_nan` argument of the numpy [allclose](https://numpy.org/doc/stable/reference/generated/numpy.allclose.html) function has False as default value.

I know... but it is still annoying. We might want to diverge from numpy on this one, like we did for aggregates.

**Comment by alixdamman** [comment]
> We might want to diverge from numpy on this one, like we did for aggregates.

OK.
