### ISSUE TITLE
implement Axis.min and Axis.max

### ISSUE THREAD

**Issue by gdementen** [larray-project/larray#874]
or more generally make Axis as much like Array as possible. Maybe making Axis inherit from Array would be possible?

**Comment by alixdamman** [comment]
What to do when labels are not integers or numeric ?

**Comment by alixdamman** [comment]
> Maybe making Axis inherit from Array would be possible?

So it is maybe the right time to implement some kind of super Abstract class for LArray objects (like `pandas` and `xarray` do)?
But that's another issue.
