### ISSUE TITLE
Replace pytest-pep8 plugin by pytest-flake8?

### ISSUE THREAD

**Issue by alixdamman** [larray-project/larray#889]
It sounds like ``pytest-pep8`` is no longer compatible with the last version of ``pytest`` (6.0.1) and is [no longer maintain](https://pypi.org/project/pytest-pep8/#history).

From the Travis job test https://travis-ci.org/github/larray-project/larray/jobs/721340978 of my last PR (PR #888), one can read the error message:
```
============================= test session starts ==============================

platform linux -- Python 3.6.11, pytest-6.0.1, py-1.9.0, pluggy-0.13.1 -- /home/travis/miniconda/envs/travisci/bin/python

cachedir: .pytest_cache

rootdir: /home/travis/build/larray-project/larray, configfile: setup.cfg, testpaths: larray

plugins: pep8-1.0.6

collected 0 items / 1 error                                                    

==================================== ERRORS ====================================

________________________ ERROR collecting test session _________________________

../../../miniconda/envs/travisci/lib/python3.6/site-packages/pluggy/hooks.py:286: in __call__

    return self._hookexec(self, self.get_hookimpls(), kwargs)

../../../miniconda/envs/travisci/lib/python3.6/site-packages/pluggy/manager.py:93: in _hookexec

    return self._inner_hookexec(hook, methods, kwargs)

../../../miniconda/envs/travisci/lib/python3.6/site-packages/pluggy/manager.py:87: in <lambda>

    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,

../../../miniconda/envs/travisci/lib/python3.6/site-packages/pytest_pep8.py:38: in pytest_collect_file

    return Pep8Item(path, parent, pep8ignore, config._max_line_length)

../../../miniconda/envs/travisci/lib/python3.6/site-packages/_pytest/nodes.py:95: in __call__

    warnings.warn(NODE_USE_FROM_PARENT.format(name=self.__name__), stacklevel=2)

E   pytest.PytestDeprecationWarning: Direct construction of Pep8Item has been deprecated, please use Pep8Item.from_parent.

E   See https://docs.pytest.org/en/stable/deprecations.html#node-construction-changed-to-node-from-parent for more details.

=========================== short test summary info ============================

ERROR  - pytest.PytestDeprecationWarning: Direct construction of Pep8Item has...

!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!

=============================== 1 error in 0.10s ===============================

The command "pytest" exited with 2.
```  

Since ``pytest-pep8`` is no longer maintain, I don't think we do anything except force to downgrade the used version of ``pytest`` but this workaround will not last forever and I don't like to get stuck with old stuff.

I suggest to replace ``pytest-pep8`` by ``pytest-flake8`` which provides an [option flake8-ignore](https://github.com/tholo/pytest-flake8#configuring-flake8-options-per-project-and-file) similar to the option `pep8ignore` of pytest-pep8. 

@gdementen  What do you think?

**Comment by gdementen** [comment]
I don't want to use an unmaintained package either. So using flake8 with some ignores to avoid having too many warnings seems like a good idea. Stopping the pep8 checks during the CI tests is another option.

**Comment by JoeCSykes** [comment]
Use pycodestyle instead. PEP8 was updated and renamed pycodestyle to be more descriptive (see https://pypi.org/project/pycodestyle/)

**Comment by gdementen** [comment]
@JoeCSykes : hi. Thanks for the pointer. Does using pycodestyle provide any advantage over pytest-flake8?

**Comment by JoeCSykes** [comment]
Not to my knowledge apart from you just type "pycodestyle" rather than "pytest -q  --flake8". One slight difference is when using flake8 it tells you a file has passed by returning PASSED but pycodestyle will only return the errors if they exist, otherwise it doesn't return anything. Also, I found I didn't have to use any ignores when using pycodestyle.

In the end I suppose it is personal preference, but I would recomend installing pycodestyle and giving it a go to compare properly.

**Comment by gdementen** [comment]
Well, we are very time-constrained, so unless there is a net advantage of switching to pycodestyle and that advantage is large enough to be greater than the cost of the switch, we will just keep using what currently works, i.e. pytest-flake8.
