### ISSUE TITLE
Make a release

### ISSUE THREAD

**Issue by gdementen** [larray-project/larray#898]
We need a release supporting python 3.8 and 3.9. Support is there in master but we have no release. This has just become more critical because the default python version in mini/anaconda is now 3.8, so it means larray cannot be installed on a default conda install

Unsure whether we make that a 0.32.3 release or a smaller than expected 0.33 release

**Comment by alixdamman** [comment]
IMO, there is not enough new improvements/features to flag the new release as 0.33.
I would flag it 0.32.3.

But, to be honest, our users do not care (at all).

**Comment by gdementen** [comment]
> But, to be honest, our users do not care (at all).

Not so sure... Of course they don't know they care 😄 but I just told DR to try to "follow the instructions" in the wiki to install larray himself on PJK's machine and it failed miserably so now I feel ridiculous 😢. We will have the same problem for each person getting a new machine, installing python for the first time or upgrading their python installation. And for persons outside our institution (e.g. the croatian team) this is worse because we have no idea when that will happen.

**Comment by alixdamman** [comment]
I meant they don't care if the new release is named 0.32.3 or 0.33
As long as the new release supports Python 3.8, it could be 0.32.3 or 0.33

By the way, I had the same problem with the installation of Python+LArray on the LL's machine. 
I rapidly realized what was happening and switched immediatly to Python 3.7
Unfortunately, I completely forget that we will have new installations to make (lake of sleep is bad). Sorry.

**Comment by gdementen** [comment]
> I meant they don't care if the new release is named 0.32.3 or 0.33

Oh, indeed 😄

**Comment by gdementen** [comment]
FWIW, it already works fine unmodified for Python 3.9.

Tested using: "conda install pandas xlwings pytables qtpy pyqt matplotlib qtconsole"
then "pip install larray-editor".

We should really make larray-* noarch packages (like is the case for the condaforge packages), which would solve this kind of problem nicely (until we introduce cython code for performance but that's not planned in the immediate future)

**Comment by gdementen** [comment]
Python 3.8 support fixed in 4e4458e55a089d20e89dcdb53ee6c87ea95fd053
Python 3.9 will be fixed in 0.33
