### ISSUE TITLE
*_by function break when specifying all axes

### ISSUE THREAD

**Issue by gdementen** [larray-project/larray#913]
```python
>>> arr = ndtest(3)
>>> arr.sum_by('a')
3
```

There is an ugly workaround but that is not user-friendly at all:

```python
>>> arr.expand('b=b0').sum_by('a')
a  a0  a1  a2
    0   1   2
```

**Comment by alixdamman** [comment]
Why would you like to "sum_by" all axes ? It doesn't make any sense to me.

**Comment by gdementen** [comment]
> Why would you like to "sum_by" all axes ? It doesn't make any sense to me.

It's obviously not on an interactive console but the _by functions are meant to work even when you do not know the axes your array has (you only know it has some required axes but could have more) and this is exactly the case one of our users stumbled into when he wrote some long reporting function which used sum_by, then passed arrays with different axes to it and it worked fine until he passed an array which had **only** the required axes.

**Comment by alixdamman** [comment]
> this is exactly the case one of our users stumbled into when he wrote some long reporting function which used sum_by, then passed arrays with different axes to it and it worked fine until he passed an array which had only the required axes.

Now it makes sense to me. Thanks for the explanation.
