### ISSUE TITLE
Unittests relying on the xlrd lib fail -> skip xlrd ?

### ISSUE THREAD

**Issue by alixdamman** [larray-project/larray#915]
The `xlrd` does no longer support other extension than `.xls` for Excel files.

From this [link](https://pypi.org/project/xlrd/):
> This library will no longer read anything other than .xls files. For alternatives that read newer file formats, please see http://www.python-excel.org/.

@gdementen Do we remove `xlrd` from the installed libraries in the .travis.yml script and skip unittest relying on `xlrd` ?
Or we adapt the unittests ?

**Comment by gdementen** [comment]
can't we replace xlrd by openpyxl in .travis.yml and avoid changing anything else in our tests?

**Comment by alixdamman** [comment]
> can't we replace xlrd by openpyxl in .travis.yml and avoid changing anything else in our tests?

We also need to replace `needs_xlrd` by `needs_openpyxl`.

The question is more about do we still want to support the old `.xls` format ? 
In other words, do our users still receive Excel documents in the `.xls` format from outside ?

**Comment by gdementen** [comment]
I don't know. In any case, it does not cost us much to leave xlrd in larrayenv but we can get away without adding an explicit test for .xls files I think.

**Comment by alixdamman** [comment]
> I don't know. In any case, it does not cost us much to leave xlrd in larrayenv but we can get away without adding an explicit test for .xls files I think.

OK
