### ISSUE TITLE
Array getitem generates FuturWarning messages (numpy)

### ISSUE THREAD

**Issue by alixdamman** [larray-project/larray#936]
line `res_data = self.data[raw_broadcasted_key]` from ``Array.__getitem__`` generates the following FuturWarning messages:
> FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.

**Comment by gdementen** [comment]
This is not the only warning and I am currently working on fixing them all.

**Comment by alixdamman** [comment]
OK. Nice.

Is fixing all warnings referenced by an issue ?
In other words, do we close the current issue or do we rename it as "fix multiple warnings" ?

**Comment by gdementen** [comment]
I couldn't find such an issue, but it does not matter much. Creating an issue after fixing it always seemed counter-productive to me.

**Comment by gdementen** [comment]
fixed by #938
