### ISSUE TITLE
fix our CI problems

### ISSUE THREAD

**Issue by gdementen** [larray-project/larray#939]
Travis CI is getting "less free". You need to explicitly ask for OSS credits regularly. We received 10000 free credits when migrating the project from travis-ci.org to travis-ci.com but this is a one shot and I fear those will quickly run out. We should either ask for OSS credits or migrate to something else. I have seen a few projects migrate to Github actions. Maybe that's worth a try.

**Comment by alixdamman** [comment]
Documentation of `Github Actions` is [here](https://docs.github.com/en/actions)

**Comment by alixdamman** [comment]
The limit for a Github Free account is [2,000 GitHub Actions minutes](https://docs.github.com/en/get-started/learning-about-github/githubs-products#github-free-for-user-accounts)

**Comment by gdementen** [comment]
AFAIU from around the web, we can't expect to get OSS credits on Travis CI anytime soon. Only the biggest projects do get them. It seems to be a case of a company being bought by investors, and the new owners start killing free services to maximize profit.

In short, it's either we pay, we move to Github actions or we stop using a CI service.

**Comment by gdementen** [comment]
#945 runs CI test for Python 3.8 I will try to expand that to other Python versions

**Comment by alixdamman** [comment]
> It seems to be a case of a company being bought by investors, and the new owners start killing free services to maximize profit.

History always repeats itself. Sad but true.

**Comment by gdementen** [comment]
> The limit for a Github Free account is 2,000 GitHub Actions minutes

FWIW, as far as I understand the monthly limit does not apply to public repositories !
